name: "Asset & readme deployment"
on:
  push:
    branches:
      - master
    paths:
      - "assets/**"
      - "src/txt/readme.txt"
jobs:
  deploy:
    name: "Upload assets & readme to wordpress.org"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            assets
            src/txt/readme.txt

      - name: "Move readme to root"
        run: |
          mv src/txt/readme.txt readme.txt

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install subversion

      - name: WordPress Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-asset-update@2.1.3
        env:
          ASSETS_DIR: assets
          IGNORE_OTHER_FILES: true
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
